### ISSUE TITLE
Second argument in `AlbedoMoMoRenderer(model, 10.0)`

### ISSUE THREAD

**Issue by vikasTmz** [waps101/AlbedoMM#3]
What is the second argument (10.0) in `AlbedoMoMoRenderer(model, 10.0)` @ [faces.apps.AlbedoModelFit](https://github.com/waps101/AlbedoMM/blob/master/scala/src/main/scala/faces/apps/AlbedoModelFit.scala#L16) ?

**Comment by BernhardEgger** [comment]
Hi vikasTmz,

it is the specular exponent
https://github.com/waps101/AlbedoMM/blob/master/scala/src/main/scala/faces/lib/AlbedoMoMoRenderer.scala

Best
Bernhard

**Comment by vikasTmz** [comment]
Thanks!
