### ISSUE TITLE
Introduce custom geometry into the fitting process

### ISSUE THREAD

**Issue by vikasTmz** [waps101/AlbedoMM#4]
How can I use a custom face geometry (which has been registered and processed to BFM template) in the inverse rendering pipeline instead of the current estimated geometry? i.e for a given face image, I have the geometry (acquired from a capture setup) which complies with BFM and want to use your inverse rendering pipeline to estimate the diffuse and specular component.

I'd be grateful if you could point me to the block of code that concerns the above.

**Comment by BernhardEgger** [comment]
The idea is simple, you fix the shape in the inference to the one you have.
It needs a bit of code adaptation.
Are you familiar with scala?
This tutorial would give you a good start
https://gravis.dmi.unibas.ch/PMM/lectures/fitting/

Is this something you want to do once, or do you plan to then improve on this?
In case it is just once, we can also quickly sit together and just do it

**Comment by vikasTmz** [comment]
> Are you familiar with scala?

Unfortunately, no. But if the adaptation is simply enough, I could figure it out.

> Is this something you want to do once, or do you plan to then improve on this?

I don't plan on improving it as of now, so getting the results from the current pipeline will suffice.

**Comment by BernhardEgger** [comment]
Let's just quickly do that together

I would ask you to install IntelliJ idea community edition and clone the repository. We can then hack it together via teamviewer?
If that makes sense contact me via egger@mit.edu to set up a coding session (pure coding should be done in 10 min if all goes smooth)
