### ISSUE TITLE
What do the rgb values in the specular map correspond to?

### ISSUE THREAD

**Issue by vikasTmz** [waps101/AlbedoMM#5]
- Do they represent parameters of a reflectance model?
- the specular exponent? Is this the exponent from the Phong model?

Edit: I apologize if this is addressed somewhere, but I couldn't find it in the paper.

**Comment by waps101** [comment]
Thanks for the question. The RGB values in the specular model can be thought of as a "specular albedo". While this is not a precisely defined physical quantity, it's useful in practice for scaling the relative specular/diffuse contribution for different parts of the face. In practice, you use it to scale a specular term. So, let's say you were using the Blinn-Phong model. You would need to choose the exponent yourself (or optimise it to fit an image) but the specular term itself, i.e. n.h^eta, can then be scaled by the specular albedo. If you want to read more about what the specular map is actually measuring, take a look at the original lightstage papers:

https://vgl.ict.usc.edu/Research/FaceScanning/

This is roughly the same setup we use and their specular map is measuring the same thing as the ones we use to build the specular model.

**Comment by vikasTmz** [comment]
Thanks!

**Comment by 07hyx06** [comment]
> Thanks for the question. The RGB values in the specular model can be thought of as a "specular albedo". While this is not a precisely defined physical quantity, it's useful in practice for scaling the relative specular/diffuse contribution for different parts of the face. In practice, you use it to scale a specular term. So, let's say you were using the Blinn-Phong model. You would need to choose the exponent yourself (or optimise it to fit an image) but the specular term itself, i.e. n.h^eta, can then be scaled by the specular albedo. If you want to read more about what the specular map is actually measuring, take a look at the original lightstage papers:
> 
> https://vgl.ict.usc.edu/Research/FaceScanning/
> 
> This is roughly the same setup we use and their specular map is measuring the same thing as the ones we use to build the specular model.

Hi, thanks for the explanation of the specular albedo. Is it means that the specular albedo can be used to set the relative scale among different vertices? 

E.g., v1 and v2 are two vertices with specular albedo s1 and s2. Suppose we use the Bling Phong model, then the specular intensity for v1 and v2 can be `s1 and s2` or `2 x s1 and 2 x s2` or `1.2 x s1 and 1.2 x s2` or something else. Is it means that the global scale of the specular intensity for each vertex is unclear, but the relative scale is expressed by the specular albedo?
