### ISSUE TITLE
Generating Landmarks for Inverse Rendering [HOW TO]

### ISSUE THREAD

**Issue by ashwath98** [waps101/AlbedoMM#6]
Hey, I was able to run the code on a windows machine for the samples provided in the repo.
I would like to test out inverse rendering for some in the wild images for testing purposes.
How would you guys recommend generating the required landmark for a 2D image, is manually annotating the only way? or is there a model available for prediciting these landmarks.

**Comment by BernhardEgger** [comment]
Hi,

you can use a tool to manually click landmarks:
https://github.com/unibas-gravis/landmarks-clicker
Or e.g. openpose to automatically detect them. You however need to bring them in the right format

Best
Bernhard

**Comment by ashwath98** [comment]
Thank you
